FROM node:24-bookworm-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /app

RUN corepack enable

COPY package.json pnpm-workspace.yaml turbo.json tsconfig.json tsconfig.base.json tsconfig.package.json biome.json ./
COPY apps ./apps
COPY packages ./packages
COPY docs ./docs

RUN pnpm install --no-frozen-lockfile

EXPOSE 3040

CMD ["pnpm", "dev:admin-api"]
