FROM oven/bun:1.1.38

WORKDIR /app

COPY package.json tsconfig.json biome.json ./
COPY apps ./apps
COPY packages ./packages

RUN bun install

EXPOSE 3040

CMD ["bun", "--cwd", "apps/admin-api", "run", "dev"]
